### ISSUE TITLE
No filters to find complete transaction

### ISSUE THREAD

**Issue by Themoonroy** [bKash-developer/bKash-for-woocommerce#2]
There is no filter for complete transactions, The records of all the statuses are also random in such a way that you cannot see complete transaction without search, Absolutely horrible.
See below..... 👇
<a href="https://ibb.co/g43WXFt"><img src="https://i.ibb.co/SfPm17V/IMG-20210919-161837.jpg" alt="IMG-20210919-161837" border="0" /></a>

**Comment by shahnawaz-ahmed** [comment]
Filter added
